#! /usr/bin/env sh
# Builds and installs bspwm and sxhkd

sudo apt-get -y update && sudo apt-get -y install git \
  xcb \
  libxcb-util0-dev \
  libxcb-ewmh-dev \
  libxcb-randr0-dev \
  libxcb-icccm4-dev \
  libxcb-keysyms1-dev \
  libxcb-xinerama0-dev \
  libasound2-dev \
  libxcb-xtest0-dev \
  gcc \
  make

mkdir bspwm-build && cd bspwm-build
git clone https://github.com/baskerville/bspwm.git
git clone https://github.com/baskerville/sxhkd.git

cd bspwm
git checkout 0.9.3
make
sudo make install

cd ../sxhkd
make
sudo make install

cd ../../
sudo cp bspwm-build/bspwm/contrib/freedesktop/bspwm.desktop /usr/share/xsessions/
rm -rf bspwm-build
