#! /usr/bin/env sh

sudo add-apt-repository -y ppa:snwh/pulp
sudo apt-get -y update
sudo apt-get -y install paper-icon-theme paper-cursor-theme
# Note: paper-gtk-theme is now abandoned and no longer supported
