#! /usr/bin/env sh
# Copyright (C) 2007 Guillaume Doré <https://github.com/Corwind/termite-install>
# Slight modifications were made to appease this repositories folder structure.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

sudo apt-get install -y \
  git \
  g++ \
  libgtk-3-dev \
  gtk-doc-tools \
  gnutls-bin \
  valac \
  intltool \
  libpcre2-dev \
  libglib3.0-cil-dev \
  libgnutls28-dev \
  libgirepository1.0-dev \
  libxml2-utils \
  gperf

mkdir termite-build && cd termite-build

git clone --recursive https://github.com/thestinger/termite.git
git clone https://github.com/thestinger/vte-ng.git

echo export LIBRARY_PATH="/usr/include/gtk-3.0:$LIBRARY_PATH"
cd vte-ng && ./autogen.sh && make && sudo make install
cd ../termite && make && sudo make install
sudo ldconfig
sudo mkdir -p /lib/terminfo/x; sudo ln -s \
/usr/local/share/terminfo/x/xterm-termite \
/lib/terminfo/x/xterm-termite

cd ../../ && rm -rf termite-build
