#! /bin/sh

for monitor in $(bspc query -M); do
  bspc monitor $monitor -d I II III IV V VI VII VIII IX X
done

bspc config border_width 4
bspc config window_gap 16

bspc config normal_border_color '#000000'
bspc config active_border_color '#444444'
bspc config focused_border_color '#FFFFFF'
bspc config presel_feedback_color '#6C7A89'

bspc config borderless_monocle true
bspc config click_to_focus any
bspc config gapless_monocle true
bspc config split_ratio 0 .50

sxhkd &
compton &

wal -tR
~/.config/polybar/launch.sh

