#! /bin/sh

for monitor in $(bspc query -M); do
  bspc monitor $monitor -d I II III IV V VI VII VIII IX X
done

bspc config border_width 4
bspc config window_gap 0

bspc config normal_border_color '#000000'
bspc config active_border_color '#444444'
bspc config focused_border_color '#FFFFFF'
bspc config presel_feedback_color '#6C7A89'

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config single_monocle true
bspc config click_to_focus any
bspc config split_ratio 0.50

sxhkd &
compton &
redshift &

# Apply last-known wallpaper. Fallback incase last colorscheme (wal -R) did not
# have a wallpaper associated with it.
if [ -f "$HOME/.cache/wal/wal" ]; then
  feh --bg-fill $(cat "$HOME/.cache/wal/wal")
fi

wal -R -o "$HOME/scripts/wal-update"
~/.config/polybar/launch.sh
dropbox start
