#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 4
bspc config window_gap 16

bspc config normal_border_color '#000000'
bspc config active_border_color '#444444'
bspc config focused_border_color '#FFFFFF'
bspc config presel_feedback_color '#6C7A89'

bspc config borderless_monocle true
bspc config click_to_focus any
bspc config gapless_monocle true
bspc config split_ratio 0 .50

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sxhkd &

